FIND_PROGRAM(
  DOXYGEN_COMMAND
  doxygen
  PATHS /usr/bin /usr/local/bin /opt/local/bin
)

SET(DOXYGEN_FOUND FALSE)
IF(DOXYGEN_COMMAND)
  SET(DOXYGEN_FOUND TRUE)
  MESSAGE(STATUS "Found Doxygen: ${DOXYGEN_COMMAND}")
  MARK_AS_ADVANCED(DOXYGEN_FOUND)
ELSE(DOXYGEN_COMMAND)
  MESSAGE(FATAL_ERROR "Doxygen not found - Please install Doxygen")  
ENDIF(DOXYGEN_COMMAND)
  
